

<div class="help-wrap">
    <div class="link-sec">
        <h2>Need Assistance?</h2>
        <ul>
                <li><a href="#">How credit system works</a></li>
                <li><a href="#">Lorem Ipsum</a></li>
                <li><a href="#">How credit system works</a></li>
        </ul>
    </div>
    <div class="contact-info-sec">
            <div class="contact-info-link">
                <span class="icon-phone1"></span>
                <div class="contact-link">
                    <span>Helpline</span>
                    <a href="tel:1.86.207.3333">1.86.207.3333</a>
                </div>
            </div>
            <div class="contact-info-link">
                <span class="icon-envelope"></span>
                <div class="contact-link">
                    <span>Email</span>
                    <a href="mailto:123@drreddy.com">123@drreddy.com</a>
                </div>
            </div>
    </div>
</div>